server:
  port: ${env.dev1port}
  servlet:
   session:
     cookie:
       name: SESSIONMISCOONE${server.port}
#服务的名称
spring:
  application:
    name: misco-product
  jpa:
    show-sql: true
      #配置zipkin
  zipkin:
    #base-url: http://localhost:9411/ #zipkin的服务的地址
    sender:
      #type: web  #已http的请求方式发送到我们的zipkin server
      type: rabbit
  sleuth:
    sampler:
      probability: 1 #采样比例 就是链路的比例 1 标识全部 0.1 标识10分一的比例采集  
  rabbitmq: #配置rabbitmq
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener: #重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true   

eureka:
  instance:
    prefer-ip-address: true #ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip展示
    #服务提供者默认30s 心跳间隔 ，90s 内如无心跳则 任务与我宕机了 需要修改时间间隔
    lease-renewal-interval-in-seconds: 2 #心跳间隔
    lease-expiration-duration-in-seconds: 5 #10s内 如无心跳 任务宕机
  client:
    service-url:
      defaultZone: http://localhost:7048/eureka/,http://localhost:7049/eureka/ #以逗号分隔 有多少注册中心就写多少个

logging:
  level:
   #开启sprig mvc 和 sleuth 的日志
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug  
    
    
testname: dev1    
   
    


