server:
  port: 7047
  servlet:
   session:
     cookie:
       name: SESSIONMISCOORDER 
  
#服务的名称
spring: 
  application:
    name: misco-springboot
    
 
#第三种配置ApplcationContextInitializer
context:
  initializer:
    classes:  com.misco.server.initzer.MyInitiazer3
  #我们的监听器  
  listener: 
    classes:  com.misco.server.listener.T3Listener 
    
onp: ttt
annov1: a
annov2: b
jack1: add 

mook: 111  

bannermark: 我是谁？ 


#配置下我们的自定义starter
weather: 
  enable: enable
  type: 下雨
  rate: 轻微








        
