server:
  port: 7053
  servlet:
   session:
     cookie:
       name: SESSIONMISCOORDERCONSUL 
#服务的名称
spring:
  application:
    name: misco-consul-order
    
  cloud: 
    consul:
      host: 127.0.0.1 # consul 服务器的主机ip
      port: 8500 # consul 服务器的端口、
      discovery: 
        register: true #是否注册到consul
        prefer-ip-address: true #以 ip 注册到consul
        ## 注册到consul展示的服务名称 ${spring.cloud.client.ip-address}:${server.port} 这个会报错 需要唯一
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        service-name: ${spring.application.name} #当前的服务名称
        port: ${server.port} #当前服务的端口
        ip-address: ${spring.cloud.client.ip-address} #当前服务的ip地址 注册到服务的ip
