verson: '3.3'
services: #服务
  app1: #程序1
    image: liuwei.dockerhello #镜像需要有有docker file 构建
    ports: 
    - 7047:7047 #对应宿主的相对应的端口
  app2: #程序1
    image: liuwei.dockerhello #镜像需要有有docker file 构建
    ports: 
    - 7048:7047 #对应宿主的相对应的端口
  