server:
  port: 7060
  servlet:
   session:
     cookie:
       name: SESSIONMISCOPRODUCER 
#服务的名称
spring:
  application:
    name: misco-stream-producer
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output: # 这个是内置的发送通道
          destination: itcast-default  #指定消息发送的目的地,在rabbitmq中,发送到一个itcast-default的exchange中
        myoutput: #生产
          destination: custom-message #自定义生产通道
          #配置分区 对特定的文字进行给特定的消费者发送
          producer:
            partition-key-expression: payload #通过字符串进行区分 可以通过对象id 给特定的对象消费
            partition-count: 2 # 分区大小
        #myinput: #自消费
          #destination: custom-message #自定义生产通道
          #group: my-group #(在消费端 进行设置组名 ，同组 多实例 只有一个才会执行进行消费)
          #consumer:
            #partitioned: true #开启分区支持
          
      binders:  #配置绑定器
        defaultRabbit:
          type: rabbit
