server:
  port: 7060
  servlet:
   session:
     cookie:
       name: SESSIONMISCOPRODUCER 
#服务的名称
spring:
  application:
    name: misco-stream-producer
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: itcast-default  #指定消息发送的目的地,在rabbitmq中,发送到一个itcast-default的exchange中
      binders:  #配置绑定器
        defaultRabbit:
          type: rabbit
