server:
  port: ${env.dev2port}
  
#服务的名称
spring:
  application:
    name: misco-stream-consumer
  rabbitmq: #配置rabbitmq
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      instance-count: 2 #两台消费实例
      instance-index: 1 #当前消费实例下标 0 开始
      bindings:  
        input: #这个和output 和 input 是内置对象 这个output一样 必须相同名字 
          destination: itcast-default #自定义消息发送目的地 在rabbit 发送到一个叫做itcast-default 的交换机
        myoutput: #生产
          destination: custom-message #自定义生产通道
        myinput: #自消费
          destination: custom-message #自定义生产通道
          group: my-group #(在消费端 进行设置组名 ，同组 多实例 只有一个才会执行进行消费)
          consumer:
            partitioned: true #开启分区支持 
      binders: #配置绑定器
        defaultRabbit:
          type: rabbit 
        
        
