server:
  port: ${evn.dev2port}
#服务的名称
spring:
  application:
    name: misco-eureka-server
eureka:
  client:
    #暴露给服务端和消费端的地址，同时向另外一个注册中心 相互注册和拉取，默认注册和拉取数据 是true的 ，
    service-url:
      defaultZone: http://localhost:${evn.dev1port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 # 剔除服务间隔 4s
